title: "HYDRA: Smart Traffic Control System"
description: "HYbrid Dynamic Realtime Automation for intelligent traffic management"
theme: jekyll-theme-cayman
baseurl: "/e21-3yp-smart-traffic-control-system"