# Create _config.yml
@'
---
layout: default
permalink: index.html
repository-name: e21-3yp-smart-traffic-control-system
title: "HYDRA: HYbrid Dynamic Realtime Automation"
---
'@ | Out-File -FilePath _config.yml -Encoding UTF8